In [133]:
import numpy as np
import pandas as pd

In [134]:
X = np.array([
    [1,-2,0,-1],
    [0,1.5,-0.5,-1],
    [-1,1,0.5,-1]
])
d = [-1, -1, 1]
c = 0.1
w = [1, -1, 0, 0.5]

In [135]:
class DeltaLearningModel:
    def __init__(self, c = 0.1, epochs = 1000) -> None:
        self.c = c
        self.epochs = epochs
        self.weight = None
    
    def train(self, X, d, w = None):
        if w is None:
            w = np.zeros(len(X[0]))
        for k in range(self.epochs):
            for i in range(len(X)):
                net = np.dot(w, X[i])
                o = self.fun(net)
                f = self.fun_dev(o)
                w += c * (d[i] - o) * f * X[i]
        self.weight = w
    
    def predict(self, X):
        y_pred = np.array([])
        for i in range(len(X)):
            # print(np.dot(self.weight, X[i]))
            # print(self.fun(np.dot(self.weight, X[i])))
            o = self.fun(np.dot(self.weight, X[i]))
            y_pred = np.append(y_pred, o)
        return y_pred
    
    @staticmethod
    def accuracy(y_pred, y_org):
        total = len(y_pred)
        correct = 0
        for i in range(total):
            if y_pred[i] == y_org[i]:
                correct += 1
        return (correct / total) * 100
    
    @staticmethod
    def precision(y_pred, y_org):
        tp = 0
        fp = 0
        for i in range(len(y_pred)):
            if y_pred[i] == 1:
                if y_pred[i] == y_org[i]:
                    tp += 1
                else:
                    fp += 1
        return tp / (tp + fp)
    
    @staticmethod
    def recall(y_pred, y_org):
        tp = 0
        fn = 0
        for i in range(len(y_pred)):
            if y_pred[i] == 1 and y_org[i] == 1:
                tp += 1
            if y_pred[i] == -1 and y_org[i] == 1:
                fn += 1
        return tp / (tp + fn)
    
    @staticmethod
    def fun(net, alpha = 0.01):
        return (2 / (1 + np.exp(-net * alpha))) - 1
    
    @staticmethod
    def fun_dev(o):
        return (1 - np.square(o)) / 2

In [136]:
model = DeltaLearningModel()
model.train(X, d, w)
model.weight

array([-63.04081495,  17.80096271,  42.77990045,  35.74641087])

In [137]:
y_pred = model.predict(X)
y_pred

array([-0.58625834, -0.15101072,  0.32069948])

In [138]:
data = pd.read_csv("../data/diabetes.csv")
data["Outcome"] = data["Outcome"].replace(0, -1)
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,-1
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,-1
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,-1
764,2,122,70,27,0,36.8,0.340,27,-1
765,5,121,72,23,112,26.2,0.245,30,-1
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,-1

In [139]:
train_data = data.iloc[:int(len(data)*0.9)]
train_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,-1
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,-1
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
686,3,130,64,0,0,23.1,0.314,22,-1
687,1,107,50,19,0,28.3,0.181,29,-1
688,1,140,74,26,180,24.1,0.828,23,-1
689,1,144,82,46,180,46.1,0.335,46,1
690,8,107,80,0,0,24.6,0.856,34,-1

In [140]:
test_data = data.iloc[int(len(data)*0.9):]
test_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
691,13,158,114,0,0,42.3,0.257,44,1
692,2,121,70,32,95,39.1,0.886,23,-1
693,7,129,68,49,125,38.5,0.439,43,1
694,2,90,60,0,0,23.5,0.191,25,-1
695,7,142,90,24,480,30.4,0.128,43,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,-1
764,2,122,70,27,0,36.8,0.340,27,-1
765,5,121,72,23,112,26.2,0.245,30,-1
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,-1

In [141]:
X_train = train_data.drop(axis=1, labels="Outcome")
X_test = test_data.drop(axis=1, labels="Outcome")

In [142]:
y_train = train_data["Outcome"]
y_test = test_data["Outcome"]

In [143]:
model = DeltaLearningModel()
model.train(np.array(X_train), np.array(y_train))
model.weight

/var/folders/m3/sh0q6jfn1z728bs06y40jjr40000gn/T/ipykernel_24346/2255257060.py:61: RuntimeWarning: overflow encountered in exp
  return (2 / (1 + np.exp(-net * alpha))) - 1

array([ 110.25463501,  175.87379115, -317.2395177 ,  -27.88434446,
       -159.06505833,    4.51340539,    5.33400002, -166.18946983])

In [144]:
y_pred = model.predict(np.array(X_test))
y_pred

/var/folders/m3/sh0q6jfn1z728bs06y40jjr40000gn/T/ipykernel_24346/2255257060.py:61: RuntimeWarning: overflow encountered in exp
  return (2 / (1 + np.exp(-net * alpha))) - 1

array([-1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        ,  1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        ,  1.        , -1.        , -1.        ,
        1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -0.98192462, -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        ,  0.99999477, -0.99999742,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -0.96211063, -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        ])

In [145]:
accuracy = model.accuracy(y_pred, np.array(y_test))
accuracy

55.84415584415584

In [146]:
print(model.precision(y_pred, np.array(y_test)))
print(model.recall(y_pred, np.array(y_test)))

0.3333333333333333
0.038461538461538464